### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by souporserious** [souporserious/react-aria#1]
### Roadmap
- [x] TabList, Tab, TabPanel components
- [ ] Row and Column components for tables
- [ ] Throw warnings when proper ARIA tags aren't used with components

**Comment by marcysutton** [comment]
You might want to look at [react-axe](https://github.com/dylanb/react-axe), which handles a ton of ARIA attributes.

**Comment by souporserious** [comment]
Awesome! Thanks for the link @marcysutton
